package necesse.inventory.lootTable;

import necesse.inventory.lootTable.presets.AbandonedMineChestLootTable;
import necesse.inventory.lootTable.presets.AlchemistChestLootTable;
import necesse.inventory.lootTable.presets.AnglerChestLootTable;
import necesse.inventory.lootTable.presets.BlacksmithChestLootTable;
import necesse.inventory.lootTable.presets.BodyArmorLootTable;
import necesse.inventory.lootTable.presets.BowWeaponsLootTable;
import necesse.inventory.lootTable.presets.CarpenterChestLootTable;
import necesse.inventory.lootTable.presets.CaveChestLootTable;
import necesse.inventory.lootTable.presets.CaveCryptLootTable;
import necesse.inventory.lootTable.presets.CaveRuinsLootTable;
import necesse.inventory.lootTable.presets.ChristmasPresentLootTable;
import necesse.inventory.lootTable.presets.CloseRangeWeaponsLootTable;
import necesse.inventory.lootTable.presets.CrateLootTable;
import necesse.inventory.lootTable.presets.DeepCaveChestLootTable;
import necesse.inventory.lootTable.presets.DeepCaveRuinsLootTable;
import necesse.inventory.lootTable.presets.DeepCrateLootTable;
import necesse.inventory.lootTable.presets.DungeonChestLootTable;
import necesse.inventory.lootTable.presets.FarmerChestLootTable;
import necesse.inventory.lootTable.presets.FeetArmorLootTable;
import necesse.inventory.lootTable.presets.GlaiveWeaponsLootTable;
import necesse.inventory.lootTable.presets.GlobalMobDropsLootTable;
import necesse.inventory.lootTable.presets.GreatbowWeaponsLootTable;
import necesse.inventory.lootTable.presets.GreatswordWeaponsLootTable;
import necesse.inventory.lootTable.presets.GunWeaponsLootTable;
import necesse.inventory.lootTable.presets.HeadArmorLootTable;
import necesse.inventory.lootTable.presets.HunterChestLootTable;
import necesse.inventory.lootTable.presets.IncursionBodyArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionBowWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionCloseRangeWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionCrateLootTable;
import necesse.inventory.lootTable.presets.IncursionFeetArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionGlaiveWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionGreatbowWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionGreatswordWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionHeadArmorLootTable;
import necesse.inventory.lootTable.presets.IncursionMagicWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionSummonWeaponsLootTable;
import necesse.inventory.lootTable.presets.IncursionThrowWeaponsLootTable;
import necesse.inventory.lootTable.presets.MagicWeaponsLootTable;
import necesse.inventory.lootTable.presets.OldVinylsLootTable;
import necesse.inventory.lootTable.presets.PirateChestLootTable;
import necesse.inventory.lootTable.presets.PirateDisplayStandLootTable;
import necesse.inventory.lootTable.presets.RareIncursionRewardsLootTable;
import necesse.inventory.lootTable.presets.SpearWeaponsLootTable;
import necesse.inventory.lootTable.presets.StartChestLootTable;
import necesse.inventory.lootTable.presets.StartDisplayStandLootTable;
import necesse.inventory.lootTable.presets.SummonWeaponsLootTable;
import necesse.inventory.lootTable.presets.SurfaceRuinsChestLootTable;
import necesse.inventory.lootTable.presets.TempleChestLootTable;
import necesse.inventory.lootTable.presets.ThrowWeaponsLootTable;
import necesse.inventory.lootTable.presets.ToolsLootTable;

public class LootTablePresets {
   public static LootTable globalMobDrops;
   public static LootTable christmasPresents;
   public static LootTable closeRangeWeapons;
   public static LootTable greatswordWeapons;
   public static LootTable spearWeapons;
   public static LootTable glaiveWeapons;
   public static LootTable bowWeapons;
   public static LootTable greatBowWeapons;
   public static LootTable gunWeapons;
   public static LootTable magicWeapons;
   public static LootTable throwWeapons;
   public static LootTable summonWeapons;
   public static LootTable incursionCloseRangeWeapons;
   public static LootTable incursionGreatswordWeapons;
   public static LootTable incursionGlaiveWeapons;
   public static LootTable incursionBowWeapons;
   public static LootTable incursionGreatBowWeapons;
   public static LootTable incursionMagicWeapons;
   public static LootTable incursionThrowWeapons;
   public static LootTable incursionSummonWeapons;
   public static LootTable tools;
   public static LootTable headArmor;
   public static LootTable bodyArmor;
   public static LootTable feetArmor;
   public static LootTable incursionHeadArmor;
   public static LootTable incursionBodyArmor;
   public static LootTable incursionFeetArmor;
   public static LootTable rareIncursionRewards;
   public static LootTable anglerChest;
   public static LootTable blacksmithChest;
   public static LootTable farmerChest;
   public static LootTable alchemistChest;
   public static LootTable carpenterChest;
   public static LootTable hunterChest;
   public static LootTable startChest;
   public static LootTable startDisplayStand;
   public static LootTable surfaceRuinsChest;
   public static LootTable oldVinylsLootTable;
   public static LootTable basicCrate;
   public static LootTable snowCrate;
   public static LootTable swampCrate;
   public static LootTable desertCrate;
   public static LootTable caveCryptUniqueItems;
   public static LootTable caveCryptBloodPlateItems;
   public static LootTable caveCryptCoffin;
   public static LootTable basicCaveRuinsChest;
   public static LootTable snowCaveRuinsChest;
   public static LootTable swampCaveRuinsChest;
   public static LootTable desertCaveRuinsChest;
   public static LootTable basicCaveChest;
   public static LootTable snowCaveChest;
   public static LootTable swampCaveChest;
   public static LootTable desertCaveChest;
   public static LootTable dungeonChest;
   public static LootTable pirateChest;
   public static LootTable pirateDisplayStand;
   public static LootTable basicDeepCrate;
   public static LootTable snowDeepCrate;
   public static LootTable swampDeepCrate;
   public static LootTable desertDeepCrate;
   public static LootTable deepCaveChest;
   public static LootTable deepSnowCaveChest;
   public static LootTable deepSwampCaveChest;
   public static LootTable deepDesertCaveChest;
   public static LootTable abandonedMineChest;
   public static LootTable templeChest;
   public static LootTable basicDeepCaveRuinsChest;
   public static LootTable snowDeepCaveRuinsChest;
   public static LootTable swampDeepCaveRuinsChest;
   public static LootTable desertDeepCaveRuinsChest;
   public static LootTable incursionCrate;

   public LootTablePresets() {
   }

   static {
      globalMobDrops = GlobalMobDropsLootTable.instance;
      christmasPresents = ChristmasPresentLootTable.instance;
      closeRangeWeapons = CloseRangeWeaponsLootTable.instance;
      greatswordWeapons = GreatswordWeaponsLootTable.instance;
      spearWeapons = SpearWeaponsLootTable.instance;
      glaiveWeapons = GlaiveWeaponsLootTable.instance;
      bowWeapons = BowWeaponsLootTable.instance;
      greatBowWeapons = GreatbowWeaponsLootTable.instance;
      gunWeapons = GunWeaponsLootTable.instance;
      magicWeapons = MagicWeaponsLootTable.instance;
      throwWeapons = ThrowWeaponsLootTable.instance;
      summonWeapons = SummonWeaponsLootTable.instance;
      incursionCloseRangeWeapons = IncursionCloseRangeWeaponsLootTable.instance;
      incursionGreatswordWeapons = IncursionGreatswordWeaponsLootTable.instance;
      incursionGlaiveWeapons = IncursionGlaiveWeaponsLootTable.instance;
      incursionBowWeapons = IncursionBowWeaponsLootTable.instance;
      incursionGreatBowWeapons = IncursionGreatbowWeaponsLootTable.instance;
      incursionMagicWeapons = IncursionMagicWeaponsLootTable.instance;
      incursionThrowWeapons = IncursionThrowWeaponsLootTable.instance;
      incursionSummonWeapons = IncursionSummonWeaponsLootTable.instance;
      tools = ToolsLootTable.instance;
      headArmor = HeadArmorLootTable.instance;
      bodyArmor = BodyArmorLootTable.instance;
      feetArmor = FeetArmorLootTable.instance;
      incursionHeadArmor = IncursionHeadArmorLootTable.instance;
      incursionBodyArmor = IncursionBodyArmorLootTable.instance;
      incursionFeetArmor = IncursionFeetArmorLootTable.instance;
      rareIncursionRewards = RareIncursionRewardsLootTable.instance;
      anglerChest = AnglerChestLootTable.instance;
      blacksmithChest = BlacksmithChestLootTable.instance;
      farmerChest = FarmerChestLootTable.instance;
      alchemistChest = AlchemistChestLootTable.instance;
      carpenterChest = CarpenterChestLootTable.instance;
      hunterChest = HunterChestLootTable.instance;
      startChest = StartChestLootTable.instance;
      startDisplayStand = StartDisplayStandLootTable.instance;
      surfaceRuinsChest = SurfaceRuinsChestLootTable.instance;
      oldVinylsLootTable = OldVinylsLootTable.instance;
      basicCrate = CrateLootTable.basicCrate;
      snowCrate = CrateLootTable.snowCrate;
      swampCrate = CrateLootTable.swampCrate;
      desertCrate = CrateLootTable.desertCrate;
      caveCryptUniqueItems = new LootTable(new LootItemInterface[]{CaveCryptLootTable.uniqueItems});
      caveCryptBloodPlateItems = new LootTable(new LootItemInterface[]{CaveCryptLootTable.uniqueBloodPlateItems});
      caveCryptCoffin = CaveCryptLootTable.instance;
      basicCaveRuinsChest = CaveRuinsLootTable.basicChest;
      snowCaveRuinsChest = CaveRuinsLootTable.snowChest;
      swampCaveRuinsChest = CaveRuinsLootTable.swampChest;
      desertCaveRuinsChest = CaveRuinsLootTable.desertChest;
      basicCaveChest = CaveChestLootTable.basicChest;
      snowCaveChest = CaveChestLootTable.snowChest;
      swampCaveChest = CaveChestLootTable.swampChest;
      desertCaveChest = CaveChestLootTable.desertChest;
      dungeonChest = DungeonChestLootTable.instance;
      pirateChest = PirateChestLootTable.instance;
      pirateDisplayStand = PirateDisplayStandLootTable.instance;
      basicDeepCrate = DeepCrateLootTable.basicDeepCrate;
      snowDeepCrate = DeepCrateLootTable.snowDeepCrate;
      swampDeepCrate = DeepCrateLootTable.swampDeepCrate;
      desertDeepCrate = DeepCrateLootTable.desertDeepCrate;
      deepCaveChest = DeepCaveChestLootTable.basicDeepCaveChest;
      deepSnowCaveChest = DeepCaveChestLootTable.snowDeepCaveChest;
      deepSwampCaveChest = DeepCaveChestLootTable.swampDeepCaveChest;
      deepDesertCaveChest = DeepCaveChestLootTable.desertDeepCaveChest;
      abandonedMineChest = AbandonedMineChestLootTable.instance;
      templeChest = TempleChestLootTable.instance;
      basicDeepCaveRuinsChest = DeepCaveRuinsLootTable.basicDeepChest;
      snowDeepCaveRuinsChest = DeepCaveRuinsLootTable.snowDeepChest;
      swampDeepCaveRuinsChest = DeepCaveRuinsLootTable.swampDeepChest;
      desertDeepCaveRuinsChest = DeepCaveRuinsLootTable.desertDeepChest;
      incursionCrate = IncursionCrateLootTable.instance;
   }
}
